import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { once } from 'node:events';
import { randomUUID } from 'node:crypto';
import { createReplayServer } from '../server/server.mjs';
import { run, FFMPEG, probe } from '../server/media.mjs';

test('viewer links isolate account APIs, render saved edits, and persist timed discussion', { timeout: 90000 }, async t => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'replay-watch-'));
  const fixture = path.join(directory, 'source.mp4');
  await run(FFMPEG, ['-nostdin', '-v', 'error', '-y', '-f', 'lavfi', '-i', 'testsrc2=s=320x180:r=24:d=2', '-c:v', 'libx264', '-preset', 'ultrafast', fixture]);
  const service = await createReplayServer({ directory: path.join(directory, '.replay-data') });
  const owner = service.app.listen(0, '127.0.0.1'), viewer = service.watchApp.listen(0, '127.0.0.1');
  await Promise.all([once(owner, 'listening'), once(viewer, 'listening')]);
  t.after(async () => { service.close(); await Promise.all([new Promise(r => owner.close(r)), new Promise(r => viewer.close(r))]); await rm(directory, { recursive: true, force: true }); });
  const ownerUrl = `http://127.0.0.1:${owner.address().port}`, viewerUrl = `http://127.0.0.1:${viewer.address().port}`;
  const request = (base, route, method = 'GET', body) => fetch(base + route, { method, headers: { 'Content-Type': 'application/json' }, body: body && JSON.stringify(body) });
  const form = new FormData(); form.append('video', new Blob([await readFile(fixture)]), 'source.mp4');
  const asset = await (await fetch(ownerUrl + '/api/assets/import', { method: 'POST', body: form })).json();
  await request(ownerUrl, `/api/assets/${asset.id}`, 'PATCH', { folder: 'PRIVATE FOLDER', comments: [{ text: 'PRIVATE NOTE', time: .2 }], edits: { trimStart: .5, trimEnd: 1.5, speed: 2 }, transcript: [{ start: 0, end: .4, text: 'CUT SECRET' }, { start: .5, end: 1.5, text: 'Shared words' }] });
  const share = await (await request(ownerUrl, `/api/assets/${asset.id}/watch`, 'POST', {})).json();
  const token = new URL(share.url).searchParams.get('watch'), route = `/api/watch/${token}`;
  assert.match(token, /^[a-f0-9]{64}$/);
  assert.equal((await (await request(ownerUrl, `/api/assets/${asset.id}/watch`, 'POST', {})).json()).url, share.url, 'reopening does not replace the discussion');
  let data;
  for (let i = 0; i < 300; i++) { data = await (await request(viewerUrl, route)).json(); if (data.status === 'completed') break; assert.ok(['queued', 'running'].includes(data.status)); await new Promise(r => setTimeout(r, 100)); }
  assert.equal(data.status, 'completed'); assert.equal(data.duration, .5);
  assert.deepEqual(data.comments, []); assert.equal(data.transcript[0].text, 'Shared words'); assert.equal(data.transcript[0].start, 0);
  for (const secret of ['PRIVATE NOTE', 'PRIVATE FOLDER', 'CUT SECRET']) assert.ok(!JSON.stringify(data).includes(secret), secret);
  for (const key of ['versions', 'sources', 'microphoneUrl', 'edits']) assert.equal(data[key], undefined);
  const rendered = await probe(service.exports.findFile(service.store.state.jobs[0].id, 'video.mp4'));
  assert.ok(Math.abs(rendered.duration - .5) < .1);
  const media = await fetch(viewerUrl + data.mediaUrl, { headers: { Range: 'bytes=0-63' } }); assert.equal(media.status, 206); assert.equal((await media.arrayBuffer()).byteLength, 64);
  for (const privateRoute of ['/api/assets', `/api/assets/${asset.id}`, '/api/settings', '/api/jobs', '/api/analytics', `/api/media/${asset.id}/video`, '/api/health']) assert.equal((await request(viewerUrl, privateRoute)).status, 404, privateRoute);
  for (const privateRoute of [`/api/assets/${asset.id}`, '/api/settings', `/api/assets/${asset.id}/watch`, '/api/exports']) assert.equal((await request(viewerUrl, privateRoute, 'POST', {})).status, 404);
  assert.equal((await request(viewerUrl, '/api/watch/' + 'a'.repeat(64))).status, 404);
  assert.equal((await request(viewerUrl, route + '/source')).status, 404);
  const comment = { id: randomUUID(), author: 'Test viewer', text: 'At this exact moment', time: .25 };
  const response = await request(viewerUrl, route + '/comments', 'POST', comment); assert.equal(response.status, 201);
  const saved = await response.json(); assert.equal(saved.time, .25); assert.ok(Date.parse(saved.createdAt));
  assert.equal((await request(viewerUrl, route + '/comments', 'POST', comment)).status, 200);
  assert.equal((await (await request(viewerUrl, route)).json()).comments.length, 1, 'retry does not duplicate');
  for (const bad of [{ time: -1 }, { time: 3 }, { time: '0.2' }, { author: '' }, { text: 'x'.repeat(2001) }]) assert.equal((await request(viewerUrl, route + '/comments', 'POST', { ...comment, ...bad, id: randomUUID() })).status, 400);
  assert.equal((await fetch(viewerUrl + route + '/comments', { method: 'POST', headers: { Origin: 'https://unrelated.example', 'Content-Type': 'application/json' }, body: JSON.stringify(comment) })).status, 403);
  await request(ownerUrl, `/api/assets/${asset.id}`, 'PATCH', { title: 'NEW PRIVATE TITLE', edits: { trimStart: 0, trimEnd: 2, speed: 1 } });
  data = await (await request(viewerUrl, route)).json(); assert.equal(data.duration, .5); assert.notEqual(data.title, 'NEW PRIVATE TITLE');
  assert.equal((await request(viewerUrl, route + '/activity', 'POST', { assetId: randomUUID(), sessionId: randomUUID(), viewerId: randomUUID(), duration: .5, watchedSeconds: .3, ranges: [[0, .5]] })).status, 200, 'activity uses the authorized snapshot');
  const disk = JSON.parse(await readFile(path.join(directory, '.replay-data', 'watch.json'), 'utf8')); assert.equal(disk.shares[0].comments[0].time, .25);
  await request(ownerUrl, `/api/assets/${asset.id}/watch`, 'DELETE');
  for (const suffix of ['', '/video', '/comments']) assert.equal((await request(viewerUrl, route + suffix, suffix === '/comments' ? 'POST' : 'GET', suffix === '/comments' ? comment : undefined)).status, 404);
  const replacement = await (await request(ownerUrl, `/api/assets/${asset.id}/watch`, 'POST', {})).json(); assert.notEqual(replacement.url, share.url);
});
